services:
  - type: web
    name: landingtest-ai-backend
    env: node
    plan: free
    buildCommand: |
      npm install
      npx playwright install chromium
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: 0
